### PR TITLE
[bundle] Fix local module refs for multi-cluster

### LINKED ISSUE #364: Local module reference fails when applying multi-clusters
When applying a bundle containing a local module reference with a multi cluster runtime, only the first cluster passes. The second one always fails with this kind of error:

```trace
11:55AM ERR module not found at path /var/folders/vl/j712bqm55gd754rr5tdm8bxm0000gn/T/timoni3063563812/gcp-eu/examples/redis
```

A simple test can be run in this repository by creating this bundle and runtime at the root of the repo:

```cue
// bundle.cue
bundle: {
	apiVersion: "v1alpha1"
	name:       "debug"
	instances: {
		redis: {
			module: url: "file://./examples/redis/"
			namespace: "default"
			values: maxmemory: 256
		}
	}
}
```

```cue
// runtime.cue
runtime: {
	apiVersion: "v1alpha1"
	name:       "production"
	clusters: {
		"first": {
			kubeContext: "local"
			group:       "test1"
		}
		"second": {
			kubeContext: "local"
			group:       "test2"
		}
	}
}
```

```shell
timoni bundle apply -f bundle.cue --runtime runtime.cue --diff
```

### PR DESCRIPTION
**Pull request by huguesalary**
This bug is caused by the relationship between the following components:
* The `func (b *BundleBuilder) InitWorkspace(workspace string,
  runtimeValues map[string]string) error` function in
  `internal/engine/bundle_builder.go`
* The `BundleBuilder.files` field
* The `BundleBuilder.mapSourceToOrigin` field
* The `func (b *BundleBuilder) getInstanceUrl(v cue.Value) string`
  function in `internal/engine/bundle_builder.go`

When called, the `InitWorkspace` goes through the list of files stored
in `b.files`, parses them and writes the result in new files (let's call
them "result files") located under the path indicated by `workspace`. In
parallel, `b.mapSourceToOrigin` maps a "result file" path to the
original file the result is based on.

At the end of the function, the original list `b.files` is replaced with
the list of "result files".

The next invocation of `InitWorkspace` then uses `b.files` again, but
this time it contains the previously computed "result files" paths.

So, for a given:
* `b.files == ["/path/to/a/bundle.cue"]`

calling `InitWorkspace("/tmp/workspace1/")`, will yield:
* `b.files == ["/tmp/workspace1/bundle.cue"]`
* `b.mapSourceToOrigin["/tmp/workspace1/bundle.cue"]="/path/to/a/bundle.cue"`

Then calling `InitWorkspace("/tmp/workspace2/")`, will yield:
* `b.files == ["/tmp/workspace2/bundle.cue"]`
* `b.mapSourceToOrigin["/tmp/workspace2/bundle.cue"]="/tmp/workspace1/bundle.cue"`

The `getInstanceUrl` relies on the `mapSourceToOrigin` being accurate to
propely resolve relative `file://` paths.

When `getInstanceUrl()` is called for the first bundle, it will propely
resolve `./examples/redis/` to `/path/to/a/examples/redis/`.

When `getInstanceUrl()` is called for the second bundle, it will erroneously
resolve `./examples/redis/` to `/tmp/workspace1/examples/redis/`.

This commit fixes this.

However it is worth noting that using a relative path for a `file://`
URI feels strange. Should it be allowed in the first place?

Fix #364

### CODE REVIEW

**Comment by huguesalary** [comment]
This fix doesn't work if `-f -` is used instead of an actual path to a file.

File: internal/engine/bundle_builder.go [hunk 1]
```diff
@@ -157,16 +156,16 @@ func (b *BundleBuilder) Build() (cue.Value, error) {
...
-			source = origin
+		dir, err := os.Getwd()
+		if err != nil {
+			return "", err
 		}
-		url = apiv1.LocalPrefix + filepath.Clean(filepath.Join(filepath.Dir(source), path))
+		url = apiv1.LocalPrefix + filepath.Clean(filepath.Join(dir, path))
 	}
-	return url
+	return url, nil
```
Comment (huguesalary) [inline internal/engine/bundle_builder.go:168]: I'm not convinced this is the right way to fix this. It feels weird to call `os.Getwd()` from inside the library. 

It seems to me the Timoni cmd package should somehow provide all the information the library needs. So, maybe `BundleBuilder` should have a new field like `cwd` pointing to the current `cwd`, instead of trying to figure it out itself.

**Comment by stefanprodan** [comment]
> However it is worth noting that using a relative path for a file:// URI feels strange. Should it be allowed in the first place?

This is how many tools work, for example Docker Compose, so I don't find it strange but actually useful.

File: internal/engine/bundle_builder.go [hunk 2]
```diff
@@ -160,11 +161,7 @@ func (b *BundleBuilder) Build() (cue.Value, error) {
 func (b *BundleBuilder) getInstanceUrl(v cue.Value) string {
 	url, _ := v.String()
 	if path := strings.TrimPrefix(url, apiv1.LocalPrefix); IsFileUrl(url) && !filepath.IsAbs(path) {
-		source := v.Pos().Filename()
-		if origin, ok := b.mapSourceToOrigin[source]; ok {
-			source = origin
-		}
-		url = apiv1.LocalPrefix + filepath.Clean(filepath.Join(filepath.Dir(source), path))
+		url = apiv1.LocalPrefix + filepath.Clean(filepath.Join(b.cwd, path))
```
Comment (stefanprodan) [inline internal/engine/bundle_builder.go:164]: We can't use CWD here, the relative path is to the bundle file (what ` v.Pos().Filename()` does) instead of the working dir of the CLI. You can see the e2e tests failing for: 

```
timoni bundle build -f hack/tests/nginx_bundle.cue --runtime-from-env

ERR module not found at path /home/runner/work/blueprints/starter
```
```

Comment (huguesalary) [reply internal/engine/bundle_builder.go]: > We can't use CWD here, the relative path is to the bundle file (what  v.Pos().Filename() does) instead of the working dir of the CLI.

Ha ok, I understand the logic better now, thanks.

This raises the issue that when the bundle file comes from Stdin (`-f -`), the `v.Pos().Filename()` becomes the temporary directory of the file Stdin was written to. Which makes the `getInstanceUrl` function fail again, since the path is now wrong.

I'm also unclear what will happen when someone specifies both a bundle via Stdin and a file (`-f- -f bundle.cue`).

I'll look into that.

Comment (stefanprodan) [reply internal/engine/bundle_builder.go]: I think we can error out if the bundle comes from stdin and contains local refs.

Comment (huguesalary) [reply internal/engine/bundle_builder.go]: Sounds good.

I removed the `cwd` code and added 4 new tests:
* bundle apply with file from stdin (`-f-`) and `module: url: file://./relative/path/to/module`
* bundle apply with file from stdin (`-f-`) and `module: url: file:///absolute/path/to/module`
* bundle apply with file from concrete file (`-f /path/to/bundle.cue`) and `module: url: file://./relative/path/to/module`
* bundle apply with file from concrete file (`-f /path/to/bundle.cue`) and `module: url: file:///absolute/path/to/module`

How's that?

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @huguesalary 🥇
